# Generated by Django 3.1.2 on 2020-10-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userdata',
            name='state',
            field=models.CharField(blank=True, choices=[('abia', 'ABIA'), ('adamawa', 'ADAMAWA'), ('akwaibom', 'AKWAIBOM'), ('anambra', 'ANAMBRA'), ('bauchi', 'BAUCHI'), ('bayelsa', 'BAYELSA'), ('benue', 'BENUE'), ('borno', 'BORNO'), ('crossriver', 'CROSSRIVER'), ('delta', 'DELTA'), ('ebonyi', 'EBONYI'), ('edo', 'EDO'), ('ekiti', 'EKITI'), ('enugu', 'ENUGU'), ('gombe', 'GOMBE'), ('imo', 'IMO'), ('jigawa', 'JIGAWA'), ('kaduna', 'KADUNA'), ('kano', 'KANO'), ('katsina', 'KATSINA'), ('kebbi', 'KEBBI'), ('kogi', 'KOGI'), ('kwara', 'KWARA'), ('lagos', 'LAGOS'), ('nasarawa', 'NASARAWA'), ('niger', 'NIGER'), ('ogun', 'OGUN'), ('ondo', 'ONDO'), ('osun', 'OSUN'), ('oyo', 'OYO'), ('plateau', 'PLATEAU'), ('rivers', 'RIVERS'), ('sokoto', 'SOKOTO'), ('taraba', 'TARABA'), ('yobe', 'YOBE'), ('zamfara', 'ZAMFARA')], max_length=30),
        ),
    ]
