# Generated by Django 3.1.2 on 2020-10-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201029_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='first_name',
            field=models.CharField(default='Adegoke', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(default='Kolawole', max_length=100),
            preserve_default=False,
        ),
    ]
